
import axios from 'axios';



export const getDraftBookingsAPI = async (user) => {
    // try {
    //     const bookings = await axios.post(`/my-bookings-draft`, user)
    //     return bookings.data
    // } catch (error) {
    //     // console.log('error while calling bookings API: ', error);

    // }
}

export const getPaidBookingsAPI = async (user) => {
    // try {
    //     const bookings = await axios.post(`/my-bookings-paid`, user)
    //     return bookings.data
    // } catch (error) {
    //     console.log('Error Occured Please Try Again Later.');

    // }
}


export const getCancelledBookings = async (user) => {
    // try {
    //     const bookings = await axios.post(`/get-cancelled-bookings`, user)
    //     return bookings.data
    // } catch (error) {
    //     console.log('Error Occured Please Try Again Later.');

    // }
}


export const deletDraftBookingsAPI = async (user) => {
    // try {
    //     const bookings = await axios.post(`/delete-draft`, user)
    //     return bookings.data
    // } catch (error) {
    //     console.log('Error Occured Please Try Again Later.');

    // }
}


export const cancelBooking = async (user) => {
    // try {
    //     const bookings = await axios.post(`/cancel-booking`, user)
    //     return bookings.data
    // } catch (error) {
    //     console.log('Error Occured Please Try Again Later.');

    // }
}